#!/bin/bash
#
# control 3GPi module
#
CONFIG=/etc/default/3gpi-utils

[ -r $CONFIG ] && . $CONFIG

VERSION="3gpictl version 1.0"

USAGE="Usage: 3gpictl [ OPTION ]

Options:
  --poweron        turn on module
  --poweroff       turn off module
  --reset          reset module
  --status         show power status
  --gpson          turn on GPS function
  --gpsoff         turn off GPS function
  --version, -v    display version and exit
  --help, -h       display help and exit
"

#
# Usage: ctl_gps [+CGPS_PARAM]
#
ctl_gps ()
{
    if [ ! -w $CONSOLE_PORT ]
    then
        echo "cannot access ${CONSOLE_PORT}"
        return 1
    fi

    stty -F $CONSOLE_PORT -icanon min 0 time 10
    echo -ne "AT+CGPS=${1}\r" > $CONSOLE_PORT
    cat $CONSOLE_PORT > /dev/null
    stty -F $CONSOLE_PORT sane
}

#
# Usage: stat_gpio [GPIO_PIN]
#
stat_gpio ()
{
    GPIO_PORT="/sys/class/gpio/gpio${1}/value"

    if [ ! -r $GPIO_PORT ]
    then
        echo "cannot access $GPIO_PORT"
        return 1
    fi

    case "$(cat $GPIO_PORT)" in
    0)
        echo "off"
        ;;
    1)
        echo "on"
        ;;
    *)
        echo "unknown"
        return 1
        ;;
    esac
}

#
# Usage: ctl_gpio [CONDITION] [GPIO_PIN] [TOGGLE_INTERVAL] [TIMEOUT]
#
ctl_gpio ()
{
    GPIO_PORT="/sys/class/gpio/gpio${2}/value"

    for i in `seq 0 $4`
    do
        STATUS=$(stat_gpio $STATUS_PIN)

        if [ $? -ne 0 ]
        then
            echo $STATUS
            return 1
        fi

        if [ $STATUS = $1 ]
        then
            if [ $i -eq 0 ]
            then
                echo "already power $1"
            fi
            return 0
        fi

        if [ ! -w $GPIO_PORT ]
        then
            echo "cannot access $GPIO_PORT"
            return 1
        fi

        if [ $i -eq 0 ]
        then
            echo 1 > $GPIO_PORT
            sleep $3
            echo 0 > $GPIO_PORT
        else
            sleep 1
        fi
    done

    echo "timeout power ${1}"

    return 1
}

#
# execute command
#
case $1 in
--poweron)
    ctl_gpio "on" "$POWER_PIN" "3" "$TIMEOUT"
    ;;
--poweroff)
    ctl_gpio "off" "$POWER_PIN" "3" "$TIMEOUT"
    ;;
--reset)
    ctl_gpio "off" "$RESET_PIN" "1" "$TIMEOUT"
    ;;
--status)
    stat_gpio "$STATUS_PIN"
    ;;
--gpson)
    ctl_gps "1,1"
    ;;
--gpsoff)
    ctl_gps "0"
    ;;
-v|--version)
    echo "$VERSION"
    ;;
-h|--help)
    echo "$USAGE"
    ;;
*)
    echo "$USAGE"
    exit 1
    ;;
esac

if [ $? -ne 0 ]
then
    echo "error: command failure"
    exit 2
fi

