#!/bin/sh

#
# control 3gpi module script
# 

VERSION="3gpictl version 0.4"

USAGE="Usage: 3gpictl [OPTION]

Options:
  --poweron        turn on 3g module
  --poweroff       turn off 3g module
  --reset          reset 3g module
  --status         show power status
  --gpson          turn on gps module
  --gpsoff         turn off gps module
  --version, -v    display version and exit
  --help, -h       display help and exit
"

POWER_PIN="17"
RESET_PIN="27"
STATUS_PIN="22"

CONSOLE="/dev/tty3GPI"

#
# Usage: stat_gpio [GPIO_PIN]
#
stat_gpio ()
{
    PORT="/sys/class/gpio/gpio${1}/value"

    if [ ! -r $PORT ]
    then
        echo "cannot access ${PORT}"
        return 1
    fi

    case "$(cat $PORT)" in
    0)
        echo "off"
        ;;
    1)
        echo "on"
        ;;
    *)
        echo "unknown"
        return 1
        ;;
    esac
}

#
# Usage: ctl_gpio [CONDITION] [GPIO_PIN] [TOGGLE_INTERVAL] [TIMEOUT]
#
ctl_gpio ()
{
    PORT="/sys/class/gpio/gpio${2}/value"

    for i in `seq 0 $4`
    do 
        STATUS=$(stat_gpio $STATUS_PIN)
        
        if [ $? -ne 0 ]
        then
            echo $STATUS
            return 1
        fi
        
        if [ $STATUS = $1 ]
        then
            if [ $i -eq 0 ]
            then
                echo "already power ${1}"
            fi
            return 0
        fi
        
        if [ ! -w $PORT ]
        then
            echo "cannot access ${PORT}"
            return 1
        fi

        if [ $i -eq 0 ]
        then        
            echo 1 > $PORT
            sleep $3
            echo 0 > $PORT
        fi
    done
    
    echo "timeout power ${1}"
    
    return 1
}

#
# Usage: ctl_gps [+CGPS_PARAM]
#
ctl_gps ()
{
    if [ ! -w $CONSOLE ]
    then
        echo "cannot access ${CONSOLE}"
        return 1
    fi

    stty -F $CONSOLE -icanon min 0 time 10
    echo -ne "AT+CGPS=${1}\r" > $CONSOLE
    cat $CONSOLE > /dev/null
    stty -F $CONSOLE sane
}

#
# execute command
#
case $1 in
--poweron)
    ctl_gpio "on" $POWER_PIN 3 30
    ;;
--poweroff)
    ctl_gpio "off" $POWER_PIN 3 30
    ;;
--reset)
    ctl_gpio "off" $RESET_PIN 1 30
    ;;
--status)
    stat_gpio $STATUS_PIN
    ;;
--gpson)
    ctl_gps "1,1"
    ;;
--gpsoff)
    ctl_gps "0"
    ;;
-v|--version)
    echo "$VERSION"
    ;;
-h|--help)
    echo "$USAGE"
    ;;
*)
    echo "$USAGE"
    exit 1
    ;;
esac

if [ $? -ne 0 ]
then
    echo "error: command failure"
    exit 1
fi

