if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi

if deb-systemd-helper --quiet debian-installed ModemManager.service \
    && deb-systemd-helper --quiet is-enabled ModemManager.service; then
	deb-systemd-invoke stop ModemManager.service >/dev/null || true
fi

if deb-systemd-helper --quiet is-enabled 3gpi-utils.service; then
	deb-systemd-invoke stop 3gpi-utils.service >/dev/null || true
fi

#DEBHELPER#
